name: New issue workflow

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign new issues and pull requests to project 1 Backlog
        uses: srggrs/assign-one-project-github-action@1.2.0
        with:
          project: 'https://github.com/nextcloud/recognize/projects/1'
          column_name: 'Backlog'

  first_comment:
    runs-on: ubuntu-latest
    name: Add first comment
    steps:
      - uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          message: |
            Hello :wave:
            
            Thank you for taking the time to open this issue with recognize. I know it's frustrating when software
            causes problems. You have made the right choice to come here and open an issue to make sure your problem gets looked at
            and if possible solved, either in the code or on your machine.
            I try to answer and fix all issues here, but it sometimes takes a while until I get to it.
            Until then, please be patient. If you can you could also look at other issues to see whether you can help
            other people with your knowledge and experience or whether others are have faced the same problem.
            One last word: If you feel, at any point, like you need to vent, this is not the place for it.
            Go to the forum, to twitter or somewhere else. This is a technical issue tracker, so please make sure to
            focus on the tech and keep your opinions to yourself. (Also see our [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/). Really.)
            
            I look forward to helping you on this issue
            Cheers :blue_heart:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
